name: Deploy Weather Telegram Bot to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Raspberry Pi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.RPI_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Deploying Weather Bot to Raspberry Pi..."
            cd /home/paios/weather_app
            git pull origin main
            source /home/paios/myenv/bin/activate
            pip install -r requirements.txt
            echo "Deployment finished!"

